// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreatePythonCode } from "./types/superchain/superchain/tx";
import { MsgDeletePythonCode } from "./types/superchain/superchain/tx";
import { MsgRunCode } from "./types/superchain/superchain/tx";
import { MsgUpdatePythonCode } from "./types/superchain/superchain/tx";

import { Params as typeParams} from "./types"
import { PythonCode as typePythonCode} from "./types"

export { MsgCreatePythonCode, MsgDeletePythonCode, MsgRunCode, MsgUpdatePythonCode };

type sendMsgCreatePythonCodeParams = {
  value: MsgCreatePythonCode,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeletePythonCodeParams = {
  value: MsgDeletePythonCode,
  fee?: StdFee,
  memo?: string
};

type sendMsgRunCodeParams = {
  value: MsgRunCode,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePythonCodeParams = {
  value: MsgUpdatePythonCode,
  fee?: StdFee,
  memo?: string
};


type msgCreatePythonCodeParams = {
  value: MsgCreatePythonCode,
};

type msgDeletePythonCodeParams = {
  value: MsgDeletePythonCode,
};

type msgRunCodeParams = {
  value: MsgRunCode,
};

type msgUpdatePythonCodeParams = {
  value: MsgUpdatePythonCode,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreatePythonCode({ value, fee, memo }: sendMsgCreatePythonCodeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePythonCode: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePythonCode({ value: MsgCreatePythonCode.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePythonCode: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeletePythonCode({ value, fee, memo }: sendMsgDeletePythonCodeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePythonCode: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePythonCode({ value: MsgDeletePythonCode.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePythonCode: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRunCode({ value, fee, memo }: sendMsgRunCodeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRunCode: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRunCode({ value: MsgRunCode.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRunCode: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePythonCode({ value, fee, memo }: sendMsgUpdatePythonCodeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePythonCode: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePythonCode({ value: MsgUpdatePythonCode.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePythonCode: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreatePythonCode({ value }: msgCreatePythonCodeParams): EncodeObject {
			try {
				return { typeUrl: "/peixer.superchain.superchain.MsgCreatePythonCode", value: MsgCreatePythonCode.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePythonCode: Could not create message: ' + e.message)
			}
		},
		
		msgDeletePythonCode({ value }: msgDeletePythonCodeParams): EncodeObject {
			try {
				return { typeUrl: "/peixer.superchain.superchain.MsgDeletePythonCode", value: MsgDeletePythonCode.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePythonCode: Could not create message: ' + e.message)
			}
		},
		
		msgRunCode({ value }: msgRunCodeParams): EncodeObject {
			try {
				return { typeUrl: "/peixer.superchain.superchain.MsgRunCode", value: MsgRunCode.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRunCode: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePythonCode({ value }: msgUpdatePythonCodeParams): EncodeObject {
			try {
				return { typeUrl: "/peixer.superchain.superchain.MsgUpdatePythonCode", value: MsgUpdatePythonCode.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePythonCode: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						PythonCode: getStructure(typePythonCode.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			PeixerSuperchainSuperchain: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;